#!/usr/bin/env bash
# A Bash script that displays Holberton School 10 times, but for the 9th iteration, displays Holberton School and then Hi on a new line.

a=0

while [ $a -lt 10 ]
do
    a=$((a + 1))
    if [[ "$a" == '4' ]]
    then
    echo 'bad luck'
    elif [[ "$a" == '8' ]]
    then
    echo 'good luck'
    else
    echo "Holberton School"
    fi
done