#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 20 with various texts in between.

a=1

while [ $a -le 20 ]
do
    echo "$a"
    (( a++ ))

    case $a in
    "5") echo "bad luck from China"
         ;;
    "10") echo "bad luck from Japan"
         ;;
    "18") echo "bad luck from Italy"
          ;;
    esac
done